---
- name: Update Windows
  hosts: all
  become: false
  gather_facts: false
  collections:
    - myllynen.windows_ansible_roles
  vars:
    #
    # Ansible WinRM configuration
    #
    #ansible_connection: winrm
    #ansible_winrm_port: 5985
    #ansible_winrm_scheme: http
    #ansible_winrm_transport: ntlm
    #ansible_winrm_message_encryption: always
    #ansible_winrm_server_cert_validation: ignore

    #ansible_winrm_user: Administrator
    #ansible_winrm_password: Foobar_12

    #
    # Ansible psrp configuration
    #
    ansible_connection: psrp
    ansible_psrp_port: 5985
    ansible_psrp_protocol: http
    ansible_psrp_auth: ntlm
    ansible_psrp_message_encryption: always
    ansible_psrp_cert_validation: ignore

    ansible_psrp_user: Administrator
    ansible_winrm_password: Foobar_12

    #
    # Ansible Windows/SSH configuration
    #
    #ansible_user: Administrator
    #ansible_password: Foobar_12
    #ansible_shell_type: powershell
    #ansible_ssh_common_args: -o GSSAPIDelegateCredentials=yes

    #
    # Common Windows connection parameters
    #
    ansible_become_method: runas
    #ansible_become_user: Administrator

    #
    # dotnet_optimize
    #
    # Compile PowerShell assemblies
    # used with Ansible connections
    dotnet_optimize_powershell: true

    # Compile all installed assemblies
    dotnet_optimize_all_assemblies: false

    #
    # system_update
    #
    # Retry attempts and delay between retries
    # for applying updates in case of failures
    system_update_retry_count: 3
    system_update_retry_delay: 30

    # Retry applying updates also if updates were
    # installed, subject to the above retry count
    system_update_retry_after_install: true

    # Parameters for win_updates
    system_update_categories: '*'
    system_update_accept_list: []
    system_update_reject_list: []
    system_update_skip_optional: true
    system_update_state: installed

    # Display update results, full or compact
    system_update_display_results: true
    system_update_display_results_full: true

    # Reboot if needed after updates
    system_update_reboot: true
    system_update_reboot_timeout: 1200

    # Compile all installed assemblies
    # This will happen only after updates
    system_update_compile_assemblies: true

    # Trigger compilation only when updates with
    # the following description were part of the
    # installed updates. Use '.*' for everything.
    system_update_compile_filter: Cumulative Update

  roles:
    - dotnet_optimize
    - system_update
