---
- name: Install updates
  vars:
    ansible_winrm_read_timeout_sec: "{{ system_update_reboot_timeout | int + 10 }}"
    ansible_winrm_operation_timeout_sec: "{{ system_update_reboot_timeout | int + 5 }}"
  become: "{{ not system_update_background_task | bool }}"
  become_method: ansible.builtin.runas
  become_user: SYSTEM
  ansible.windows.win_updates:
    category_names: "{{ system_update_categories }}"
    accept_list: "{{ system_update_accept_list | default(omit, true) }}"
    reject_list: "{{ system_update_reject_list | default(omit, true) }}"
    skip_optional: "{{ system_update_skip_optional | bool }}"
    state: "{{ system_update_state }}"
    reboot: false
  register: update_result
  ignore_errors: true
  when: >
    update_install is none or
    update_install is failed or
    (update_install is changed and
     system_update_retry_after_install | bool)

- name: Record update installation result
  ansible.builtin.set_fact:
    update_install: "{{ update_result }}"
    update_combined: "{{ update_combined |
                         combine({'updates': update_result.updates}, recursive=true) }}"
  when: update_result is not skipped

- name: Reboot system
  ansible.windows.win_reboot:
    reboot_timeout: "{{ system_update_reboot_timeout | float }}"
    post_reboot_delay: 10.0
    msg: "Ansible reboot after installing updates"
  register: reboot_status
  when:
    - update_result is not skipped
    - (system_update_reboot_always | bool and
       (update_install.reboot_required is not defined or
        update_install is failed or
        update_install is changed)) or
      (system_update_reboot | bool and
       (update_install.reboot_required is not defined or
        update_install.reboot_required or
        (update_install is failed and
         update_attempt < system_update_retry_count | int)))

- name: Record reboot status
  ansible.builtin.set_fact:
    system_update_rebooted: true
  when: reboot_status is not skipped

- name: Pause before next update attempt
  ansible.builtin.pause:
    seconds: "{{ system_update_retry_delay }}"
  when:
    - update_install is failed or
      (update_install is changed and
       system_update_retry_after_install | bool)
    - update_attempt < system_update_retry_count | int
